language: ruby
rvm:
  - 2.7.4
addons:
  postgresql: 12
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
services:
  postgres
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost:5433/library_test
script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake spec
  - bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: FyUePpaQn5lxyTNJbAm2X7is1zPAGOF5Xx/RkM5CrdIcpLbAPgvKmaour4zMAKHzwX9Y01gRZKFCa4JAYy4YWqo/9r9jSxk6HX24sV3u3bBETyaXMUYsf8r0AOMlMgNrrp4e3y652QxWBQ1TnEdeInTekj/xd/R6eH1bnMI+O+PEbPhht28CGSZdpUecSG6SZrjSojYm3tTlwHCzDPdXQqsmRwvaTjyYeO3WOOjfwTccRKdC+fLl0jYZp9gWQFOV24xdwrp6Vm6JNJ9NzG7oTQBqcPuTCXXOeJ4OeQYboV0+bhervg9hg/eExiZaw0+94fPMvv/9/sSBVEQvH20oJRKlCEE6aWPqFAl44RRaGLWLiauFcr4HfK4OMZmjO4UcUWCbrXai33T1XG6G2j/r6LR9qVWyNFkn9UaWRwdUC3XW/6dDNTJEBtv21WivTwBlmg+xGgXgPl+LhvtjraEELDWF2wQvB7GMWInXjf4K139IqfZaLStFBvxzdqExjElM7qO3/5iB89cK9/tTyIEKp9FgGD7o43yr7X3A0ibnZWOEzQdr06GEOXIRJLvFWM/N/eHxfJmHk48ob/mkzDq7dDzIg06iD6npwgJsTJOeZd45UTzvNGOteX+fAst+jfbiSnbfSx/sRSUl+6dQEjJu6HaCKYsKh8OKtsQEwBDc6ps=
  app:
    main: devlib
